---
platform: linux
image_resource:
  type: docker-image
  source: {repository: golang, tag: "1.5.4"}
inputs:
  - name: bgd-git
    path: src/github.com/romanik/cf-blue-green-deploy
  - name: version
outputs:
  - name: artefacts
run:
    path: src/github.com/romanik/cf-blue-green-deploy/script/ci/ci_build
