#!/bin/bash
# vim: set ft=sh

export CF_HOME="${CF_HOME:-$HOME}"

. script/with_env
. script/common

PLUGIN_NAME="${PLUGIN_NAME:?Must be defined in .env}"

main() {
  uninstall_plugin "$PLUGIN_NAME"
  install_plugin "$PLUGIN_NAME"
}

main
